### ISSUE TITLE
how do i connect this from a python file running inside a container ?

### ISSUE THREAD

**Issue by KaustubhJha-TUL-UpperFunnel** [nouchka/docker-sqlite3#1]
I am currently doing this using sqlalchemy 

`engine =  sql.create_engine("sqlite:///sqlite/db/riders.db")`

but it's giving error as "Unable to connect to db"

there is not a riders.db inside my db volume

how to create it using docker-compose and access it ?

**Comment by nouchka** [comment]
Hi,
I don't have any experience in python but I think you need to share the volume containing the databases between the containers. You will have a docker compose volume, your python image will mount to directory /sqlite/db and my image will mount the same volume on /root/db/
The databases will be accessible from your code in the python image and available from sqlite3 command line from my image/container.
Last solution is to install sqlite3 package directly in your python container.
